- hosts: webservers

  roles:
    - datadog.dd.agent
  vars:
    datadog_checks:
      tcp_check:
        init_config:
        instances:
          - name: Healthcheck
            host: "{{ ansible_host }}"
            port: 80
